version: '3.8'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media

    ports:
      - 1337:80
    depends_on:
      - web

  web:
    build: 
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn --workers=4 tennis.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media

    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    container_name: postgres_container
    image: postgres:13.0-alpine
    ports:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:5.5
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin



volumes:
  postgres_data:
  pgadmin-data:
  static_volume:
  media_volume:
    
