# Generated by Django 3.2 on 2022-11-03 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название турнира')),
                ('date', models.DateField(verbose_name='Дата')),
                ('location', models.CharField(max_length=100, verbose_name='Город')),
                ('category_gender', models.CharField(choices=[('male', 'Мужчины'), ('female', 'Женщины')], max_length=100, verbose_name='Категория пол')),
                ('category_age', models.CharField(choices=[('Under 14', 'До 14 лет'), ('14 and older', 'Старше 14 лет')], max_length=100, verbose_name='Категория возраст')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Описание Федерации')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название клуба')),
                ('description', models.CharField(max_length=255, verbose_name='Описание клуба')),
                ('address', models.URLField(verbose_name='Адрес клуба')),
                ('contacts', models.CharField(max_length=100, verbose_name='Контакты')),
                ('working_hours', models.CharField(max_length=100, verbose_name='Часы работы')),
                ('Instagram', models.URLField(verbose_name='Instagram')),
                ('Facebook', models.URLField(verbose_name='Facebook')),
                ('images', models.ImageField(upload_to='', verbose_name='Фото клуба')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='gallery_main_image')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок новости')),
            ],
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_photo', models.ImageField(upload_to='main_page_image')),
                ('whatsapp', models.URLField()),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Краткое название')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(verbose_name='Описание новости')),
                ('source', models.CharField(max_length=255, verbose_name='Источник')),
                ('main_photo', models.ImageField(upload_to='news_main_image', verbose_name='Главное фото')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Место')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Год рождения')),
                ('number_of_tournaments', models.IntegerField(verbose_name='Кол-во турниров')),
                ('category_gender', models.CharField(choices=[('male', 'Мужчины'), ('female', 'Женщины')], max_length=100, verbose_name='Категория пол')),
                ('category_age', models.CharField(choices=[('Under 14', 'До 14 лет'), ('14 and older', 'Старше 14 лет')], max_length=100, verbose_name='Категория возраст')),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО тренера')),
                ('description', models.CharField(max_length=255, verbose_name='Информация о тренере')),
                ('address', models.CharField(max_length=100, verbose_name='Место работы')),
                ('contacts', models.CharField(max_length=100, verbose_name='Контакты')),
                ('images', models.ImageField(upload_to='', verbose_name='Фото тренера')),
            ],
        ),
        migrations.CreateModel(
            name='NewsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='news_image', verbose_name='Фотографии')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.news')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='gallery_images')),
                ('gallery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.gallery')),
            ],
        ),
    ]
