# Generated by Django 3.2 on 2023-02-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.ImageField(default='none', upload_to='', verbose_name='Фото Федерации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainertranslation',
            name='category',
            field=models.CharField(default='images', max_length=100, verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
