# Generated by Django 3.2 on 2022-12-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='club',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='clubtranslation',
            name='description',
            field=models.TextField(verbose_name='Описание клуба'),
        ),
        migrations.AlterField(
            model_name='trainertranslation',
            name='description',
            field=models.TextField(verbose_name='Информация о тренере'),
        ),
    ]
