# Generated by Django 3.2.6 on 2022-11-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(editable=False, verbose_name='Рейтинг'),
        ),
    ]
