# Generated by Django 3.2 on 2022-11-29 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='Facebook',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='Instagram',
            new_name='instagram',
        ),
        migrations.RemoveField(
            model_name='clubtranslation',
            name='address_link',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
        migrations.AddField(
            model_name='club',
            name='address_link',
            field=models.URLField(default=1, verbose_name='Ссылка на адрес клуба'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleryimages',
            name='gallery_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='first_app.gallery'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallerytranslation',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название галерии'),
        ),
    ]
