# Generated by Django 3.2 on 2022-12-28 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationalpartners',
            name='title',
        ),
        migrations.RemoveField(
            model_name='officialpartner',
            name='title',
        ),
        migrations.RemoveField(
            model_name='sponsorsandpartners',
            name='title',
        ),
    ]
