# Generated by Django 3.2 on 2022-12-09 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20221207_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubtranslation',
            name='address',
            field=models.TextField(verbose_name='Адрес клуба'),
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='gallery_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_image', to='first_app.gallery'),
        ),
    ]
