# Generated by Django 3.2 on 2022-12-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20221228_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationalpartners',
            name='title',
            field=models.CharField(default='sponsors', max_length=100, verbose_name='Информационные партнеры Федерации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officialpartner',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='Официальный партнер Федерации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsorsandpartners',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='Спонсоры и партнеры'),
            preserve_default=False,
        ),
    ]
