# Generated by Django 3.2 on 2022-12-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20221207_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubtranslation',
            name='address',
            field=models.TextField(verbose_name='Адрес клуба'),
        ),
    ]
