# Generated by Django 3.2 on 2022-12-28 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20221228_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officialpartner',
            name='title',
        ),
        migrations.RemoveField(
            model_name='sponsorsandpartners',
            name='title',
        ),
    ]
