# Generated by Django 3.2.6 on 2022-11-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_remove_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=10, verbose_name='Рейтинг'),
            preserve_default=False,
        ),
    ]
