# Generated by Django 3.2 on 2022-12-28 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20221228_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationalpartners',
            name='title',
        ),
    ]
