# Generated by Django 3.2.6 on 2022-11-28 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
    ]
