# Generated by Django 3.2 on 2023-01-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('p_male', 'Мужской'), ('p_female', 'Женский')], max_length=100, verbose_name='Пол'),
        ),
    ]
