# Generated by Django 3.2 on 2023-01-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_player_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('мужской', 'Мужской'), ('женский', 'Женский')], max_length=100, verbose_name='Пол'),
        ),
    ]
