# Generated by Django 3.2 on 2023-04-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_player_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Пользователь с таким электронным адресом уже существует'}, max_length=254, unique=True),
        ),
    ]
